# en: To update mise, ni, and pnpm, run `mise update`.
# jp: miseやni, pnpmをアップデートしたい時は `mise update` を実行する

[tools]
node = "lts"
pnpm = "latest"
"npm:@antfu/ni" = "latest"

[env]
NODE_ENV = "development"

[settings]
# Enable automatic updates
auto_install = true

[tasks.update]
description = "Update ni and pnpm to latest version"
run = "mise upgrade"
